### ISSUE TITLE
Recommendation and offer to help

### ISSUE THREAD

**Issue by lexidor** [druid628/hack-experiment#1]
Hi @druid628,

I am the first _?_ the poor sucker who happens to stumble upon this repo.
I was just clicking through the dependents on hhvm/type-assert and found this repo.
I have been writing in Hack for about a year at this point.
I love to help people get up to speed in Hack.
If you feel like you are stuck with something, feel free to shoot me a message.
Finding help online is quite hard.
I assume that you've already found [Hack documentation](https://docs.hhvm.com/), have you?

With kind regards,

Lexidor

**Comment by druid628** [comment]
Yeah I've been going through the hack documentation at night as I've had time. 
I'm just basically trying to get my feet wet with it. I've got a plan for a project that's a little way off that I feel like hhvm would be ideal for so I'm just testing out some things and putting bits in pieces in this repo to refer back to. Hack is close enough to PHP and I've been using PHP for 20 years at this point so my learning curve isn't very sharp.

I appreciate the offer though. 
It's definitely worth knowing ppl in the hack community.

**Comment by lexidor** [comment]
Okay, keep in mind that HHVM 4.0 and up CANNOT run `<?php` code. Only `<?hh` and `.hack` code.

**Comment by druid628** [comment]
Absolutely. Yeah, I did a deep dive into investigating the language prior to starting to tinker with it.
